// Shared Bible constants used across the app

export const TRANSLATIONS: Record<string, string> = {
  NIV: "New International Version",
  ESV: "English Standard Version",
  NLT: "New Living Translation",
  KJV: "King James Version",
  NKJV: "New King James Version",
  CSB: "Christian Standard Bible",
  NASB: "New American Standard Bible",
  AMP: "Amplified Bible",
  MSG: "The Message",
};

export const EMOTION_SUGGESTIONS = [
  // Most-searched — shown first in horizontal scroll
  "anxious",
  "overwhelmed",
  "stressed",
  "lonely",
  "hopeful",
  "grateful",
  "lost",
  "afraid",
  // Difficult emotions
  "burned out",
  "depressed",
  "numb",
  "sad",
  "grieving",
  "heartbroken",
  "confused",
  "doubting",
  "purposeless",
  "ashamed",
  "angry",
  "bitter",
  "jealous",
  "hopeless",
  "disconnected",
  "exhausted",
  "broken",
  "rejected",
  "insecure",
  "worried",
  "stuck",
  "misunderstood",
  "worthless",
  "forgotten",
  // Modern / today's pressures
  "comparison trap",
  "imposter syndrome",
  "financial stress",
  "relationship struggles",
  "health anxiety",
  "trauma",
  "grief after loss",
  "digital overwhelm",
  "career pressure",
  "addiction",
  "prodigal",
  "spiritually dry",
  // 2025–2026 cultural pressures
  "AI uncertainty",
  "doomscrolling",
  "overstimulated",
  "information overload",
  "climate anxiety",
  "loneliness epidemic",
  "social media exhaustion",
  "political anxiety",
  "job uncertainty",
  "economic fear",
  "identity crisis",
  "hustle culture burnout",
  "decision fatigue",
  "FOMO",
  "people pleasing",
  "perfectionism",
  "self-doubt",
  "need for belonging",
  "chronically online",
  "purpose in uncertain times",
  "digital addiction",
  "comparison culture",
  "emotionally numb",
  "barely surviving",
  "craving stillness",
  "afraid of the future",
  "feeling behind in life",
  "can't slow down",
  // Positive emotions
  "joyful",
  "peaceful",
  "blessed",
  "thankful",
  "content",
  "excited",
  "inspired",
  "courageous",
  "loved",
  "strong",
  "victorious",
  "at peace",
  "overjoyed",
  // Spiritual states
  "seeking",
  "forgiven",
  "healing",
  "growing",
  "surrendering",
  "worshipful",
  "discerning",
  "renewed",
  "waiting on God",
  "tested",
  "restored",
  // Life transitions
  "new chapter",
  "starting over",
  "empty nest",
  "new parent",
  "newly married",
  "going through divorce",
  "job loss",
  "retirement",
  "college transition",
  "caring for aging parents",
];

export const SEARCH_SUGGESTIONS = [
  "love",
  "peace",
  "faith",
  "hope",
  "grace",
  "strength",
  "light",
  "shepherd",
  "water",
  "bread",
  "fire",
  "angel",
  "mountain",
  "heart",
  "prayer",
  "joy",
  "rest",
  "trust",
  "fear",
  "forgive",
  "wisdom",
  "refuge",
  "promise",
  "armor",
  "sword",
  "crown",
  "glory",
  "spirit",
  "truth",
  "power",
  "heal",
  "deliver",
  "chosen",
];

// 7-day reading plan themes — used for reading plan feature
export const READING_PLAN_THEMES = [
  { id: "anxiety", label: "Overcoming Anxiety", emoji: "🕊️" },
  { id: "grief", label: "Walking Through Grief", emoji: "💙" },
  { id: "hope", label: "Finding Hope", emoji: "✨" },
  { id: "identity", label: "Identity in Christ", emoji: "🌟" },
  { id: "prayer", label: "A Life of Prayer", emoji: "🙏" },
  { id: "strength", label: "Strength for the Weary", emoji: "💪" },
  { id: "faith", label: "Growing in Faith", emoji: "🌱" },
  { id: "forgiveness", label: "The Gift of Forgiveness", emoji: "🤍" },
  { id: "purpose", label: "Discovering Your Purpose", emoji: "🧭" },
  { id: "gratitude", label: "A Heart of Gratitude", emoji: "🙌" },
  { id: "relationships", label: "Loving Well", emoji: "❤️" },
  { id: "peace", label: "The Peace That Passes Understanding", emoji: "☮️" },
  { id: "digital-age", label: "Faith in the Digital Age", emoji: "📱" },
  { id: "rest", label: "Sabbath Rest in a Busy World", emoji: "🌿" },
  { id: "courage", label: "Courage for Uncertain Times", emoji: "🛡️" },
  { id: "comparison", label: "Freedom from Comparison", emoji: "🌈" },
];

// Maximum number of recent searches to store
export const MAX_RECENT_SEARCHES = 8;
